#!/bin/bash
#
# SSL Certificate Generation for PostgreSQL
# Generates self-signed SSL certificates for PostgreSQL connections
#
# Usage: sudo ./generate-cert.sh [hostname]
#

set -euo pipefail

# Configuration
HOSTNAME="${1:-$(hostname -f)}"
SSL_DIR="/var/lib/postgresql/ssl"
CERT_VALIDITY_DAYS=3650  # 10 years
KEY_SIZE=4096

# Color output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   error "This script must be run as root (use sudo)"
   exit 1
fi

log "Generating SSL certificates for PostgreSQL..."
log "Hostname: $HOSTNAME"
log "Certificate validity: $CERT_VALIDITY_DAYS days (10 years)"

# Create SSL directory if it doesn't exist
mkdir -p "$SSL_DIR"

# Generate private key
log "Generating ${KEY_SIZE}-bit RSA private key..."
openssl genrsa -out "$SSL_DIR/server.key" $KEY_SIZE

# Generate certificate signing request (CSR)
log "Generating certificate signing request..."
openssl req -new -key "$SSL_DIR/server.key" \
    -out "$SSL_DIR/server.csr" \
    -subj "/C=US/ST=State/L=City/O=CostPlusDB/OU=Database/CN=$HOSTNAME"

# Generate self-signed certificate
log "Generating self-signed certificate..."
openssl x509 -req -days $CERT_VALIDITY_DAYS \
    -in "$SSL_DIR/server.csr" \
    -signkey "$SSL_DIR/server.key" \
    -out "$SSL_DIR/server.crt"

# Set proper permissions
log "Setting secure permissions..."
chown postgres:postgres "$SSL_DIR"/*
chmod 600 "$SSL_DIR/server.key"
chmod 644 "$SSL_DIR/server.crt"
chmod 644 "$SSL_DIR/server.csr"

# Display certificate information
log "Certificate generated successfully!"
echo ""
echo "Certificate details:"
openssl x509 -in "$SSL_DIR/server.crt" -noout -subject -dates -fingerprint

# Create copy for backup
BACKUP_DIR="/home/admincostplus/projects/costplusdb/001-security/keys/ssl-ca"
mkdir -p "$BACKUP_DIR"
cp "$SSL_DIR/server.crt" "$BACKUP_DIR/server.crt.$(date +%Y%m%d)"
cp "$SSL_DIR/server.key" "$BACKUP_DIR/server.key.$(date +%Y%m%d)"

log "Backup copy stored in: $BACKUP_DIR"

# Log to audit trail
AUDIT_LOG="/home/admincostplus/projects/costplusdb/001-security/logs/audit/ssl-certificates.log"
mkdir -p "$(dirname "$AUDIT_LOG")"
cat >> "$AUDIT_LOG" << EOF
$(date +'%Y-%m-%d %H:%M:%S') - SSL Certificate Generated
Hostname: $HOSTNAME
Validity: $CERT_VALIDITY_DAYS days
Generated by: $(whoami)
Certificate fingerprint: $(openssl x509 -in "$SSL_DIR/server.crt" -noout -fingerprint | cut -d= -f2)
---
EOF

log "SSL certificate generation complete!"
warn "IMPORTANT: Update postgresql.conf with:"
warn "  ssl = on"
warn "  ssl_cert_file = '$SSL_DIR/server.crt'"
warn "  ssl_key_file = '$SSL_DIR/server.key'"

exit 0
