#!/bin/bash
#
# Import Vertex AI Generated Test Data
# Imports SQL files generated by Vertex AI into the 5 test databases
#

set -e  # Exit on error

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Importing Vertex AI Generated Data${NC}"
echo -e "${BLUE}========================================${NC}\n"

# Get directories
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"
SQL_OUTPUT_DIR="$PROJECT_ROOT/sql-output"

# Check if sql-output directory exists
if [ ! -d "$SQL_OUTPUT_DIR" ]; then
    echo -e "${YELLOW}Error: sql-output directory not found${NC}"
    echo -e "Please run the data generation script first:"
    echo -e "  ${BLUE}cd vertex-ai && python generate-test-data.py${NC}\n"
    exit 1
fi

# Database configurations
declare -A DBS
DBS[customer1]="costplusdb_customer1"
DBS[customer2]="costplusdb_customer2"
DBS[customer3]="costplusdb_customer3"
DBS[customer4]="costplusdb_customer4"
DBS[customer5]="costplusdb_customer5"

declare -A NAMES
NAMES[customer1]="E-commerce Shop"
NAMES[customer2]="SaaS Startup"
NAMES[customer3]="Blog/CMS"
NAMES[customer4]="Mobile App API"
NAMES[customer5]="Analytics Platform"

# Import data
count=0
for customer in customer1 customer2 customer3 customer4 customer5; do
    ((count++))
    DB_NAME="${DBS[$customer]}"
    CUSTOMER_NAME="${NAMES[$customer]}"
    DATA_DIR="$SQL_OUTPUT_DIR/$customer"

    echo -e "${BLUE}[$count/5] ${CUSTOMER_NAME} (${DB_NAME})${NC}"

    if [ ! -d "$DATA_DIR" ]; then
        echo -e "  ${YELLOW}Warning: No data directory found at ${DATA_DIR}${NC}"
        echo -e "  ${YELLOW}Skipping...${NC}\n"
        continue
    fi

    # Count SQL files
    SQL_FILES=("$DATA_DIR"/*.sql)
    FILE_COUNT=${#SQL_FILES[@]}

    echo "  Importing $FILE_COUNT table files..."

    # Import each SQL file
    for sql_file in "$DATA_DIR"/*.sql; do
        if [ -f "$sql_file" ]; then
            table_name=$(basename "$sql_file" .sql)
            echo -n "    - $table_name..."

            # Import with progress
            psql -d "$DB_NAME" -f "$sql_file" -q 2>&1 | grep -i error || true

            # Count rows
            row_count=$(psql -d "$DB_NAME" -t -c "SELECT COUNT(*) FROM $table_name;" 2>/dev/null || echo "0")
            echo -e " ${GREEN}${row_count} rows${NC}"
        fi
    done

    # Get total row count for database
    TOTAL_ROWS=$(psql -d "$DB_NAME" -t -c "
        SELECT SUM(n_live_tup)::bigint
        FROM pg_stat_user_tables;
    " | tr -d ' ')

    echo -e "  ${GREEN}✓ Total rows in database: ${TOTAL_ROWS}${NC}\n"
done

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Import Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo -e "\n${YELLOW}Next step:${NC}"
echo -e "  ${BLUE}./scripts/03-verify-setup.sh${NC}\n"
